
trigger:
- feature-abc1

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    jobs:
    - job: doBuild
      steps:

      - task: Maven@3
        displayName: Build with Maven
        inputs:
          mavenPomFile: 'pom.xml'
          mavenOptions: '-Xmx3072m'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.8'
          jdkArchitectureOption: 'x64'
          publishJUnitResults: false
          goals: 'clean package'

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: 'target/verademo.war'
          ArtifactName: 'upload'

  - stage: sast_sandbox_scan
    jobs:
    - job: sast_sandbox_scan
      steps:
      - task: DownloadBuildArtifacts@1
        inputs:
          artifactName: upload
      
      - task: Veracode@3
        inputs:
          ConnectionDetailsSelection: 'Credentials'
          apiId: '$(VERACODE_ID)'
          apiKey: '$(VERACODE_KEY)'
          veracodeAppProfile: '$(system.teamProject)'
          version: '$(build.buildNumber)'
          filepath: '$(build.artifactstagingdirectory)/upload/verademo.war'
          sandboxName: '$(Build.SourceBranchName)'
          createSandBox: true
          optargs: '-deleteincompletescan 2 -teams $(VERACODE_TEAMS) -criticality High'
          createProfile: true
      displayName: Veracode SAST - Sandbox Branch Scan
  
  - stage: sast_policy_scan
    jobs:
    - job: sast_policy_scan
      steps:

      - task: DownloadBuildArtifacts@1
        inputs:
          artifactName: upload
      
      - task: Veracode@3
        inputs:
          ConnectionDetailsSelection: 'Credentials'
          apiId: '$(VERACODE_ID)'
          apiKey: '$(VERACODE_KEY)'
          veracodeAppProfile: '$(system.teamProject)'
          version: '$(build.buildNumber)'
          filepath: '$(build.artifactstagingdirectory)/upload/verademo.war'
          optargs: '-deleteincompletescan 2 -teams $(VERACODE_TEAMS) -criticality High'
          createProfile: true
      displayName: Veracode SAST - Policy Scan

  - stage: sca_agent_based
    jobs:
      - job: veracode_sca
        steps:

        - task: CmdLine@2
          inputs:
            script: |
              export SRCCLR_API_TOKEN=$(SRCCLR_API_TOKEN)
              export SRCCLR_SCM_URI=$(Build.Repository.Uri)
              export SRCCLR_SCM_REF=$(Build.SourceBranchName)
              export SRCCLR_SCM_REF_TYPE="branch"
              export SRCCLR_SCM_REV=$(Build.SourceVersion)
              curl -sSL https://download.sourceclear.com/ci.sh | bash -s – scan  --allow-dirty --update-advisor --uri-as-name || true
        displayName: 'Veracode SCA - Agent-Based Scan'  

  - stage: pipeline_scan
    jobs:
    - job: sast_pipeline_scan
      steps:

      - task: DownloadBuildArtifacts@1
        inputs:
          artifactName: upload

      - task: CmdLine@2
        inputs:
          script: |
            curl -sSO https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip
            unzip -o pipeline-scan-LATEST.zip
            java -jar pipeline-scan.jar -vid $(VERACODE_ID) -vkey $(VERACODE_KEY) -f $(build.artifactstagingdirectory)/upload/verademo.war  --project_name "verademo-java-web" -r $(Build.SourceBranch) -aid $(VERACODE_PROJECT_ID) -ds "Development"
        displayName: Veracode SAST - Pipeline Scan
  
